### ISSUE TITLE
Dropdown menus revert back to default options

### ISSUE THREAD

**Issue by 7stringplayer** [dr4fters/dr4ft#1034] opened 2020-05-15 15:01 UTC
So i tried to change the packs and they end up going back to Ikoria

**Comment by tooomm** [comment] 2020-05-15 15:07
Interesting. Just tested this... and you are right. They dropdown flickers back to IKO when you create the sealed room - barely noticable. I think that's new.
But in the room description you see the right ones listed. When I started the game, the right packs appeared as well.

**Comment by 7stringplayer** [comment] 2020-05-15 15:14
Mine did not they all went to Ikoria not the set i selected

**Comment by tooomm** [comment] 2020-05-15 15:16
When do they change back to ikoria?
Which site do you use and does it currently still happen?

**Comment by 7stringplayer** [comment] 2020-05-15 15:19
Almost immediately they flock back to Ikoria.  I create the room and it says M20 and 5 IKO.  I use Dr4ft.info

**Comment by HerveH44** [comment] 2020-05-15 19:59
@keeler It may be linked to your PR. Do you have some time to check if they are linked?

**Comment by tooomm** [comment] 2020-05-15 20:47
Note: This also happens for draft. It is not a sealed only issue.

Happens in Chromium and Firefox, sometimes immediately, sometimes a bit delayed or once you click the create button.

**Comment by ZeldaZach** [comment] 2020-05-15 20:48
Server ran out of storage. I cleaned it up just now. Feel free to try again

**Comment by tooomm** [comment] 2020-05-15 20:53
Unchanged :(

**Comment by 7stringplayer** [comment] 2020-05-15 21:31
Mine seemed to work in Chrome.... no issues now

**Comment by tooomm** [comment] 2020-05-15 21:39
Works here now, too.

**Comment by tooomm** [comment] 2020-05-16 13:42
Looks like @ZeldaZach reverted dr4ft.info to a commit without the `Decadent` option.

If I look at https://beta-dr4ft.herokuapp.com/ the issue appears again and seem to be related to that change. Can you confirm @7stringplayer?
Thinking about if further... it looks like the pack selection gets reverted to default instead "remembering" the selected value and present that to the user on next visit.
Because changing the set selection, creating a room, closing the page and going to the page again presents 3xIKO again instead my last selection. It used to remember a players last selection.

CC: @keeler

**Comment by 7stringplayer** [comment] 2020-05-16 15:33
Yes on that site it  is doing what it did yesterday.  The main site is still working

**Comment by keeler** [comment] 2020-05-16 23:10
Likely related to my recent change, I can take a look this weekend.

I'm a little confused, can I get a concise description of the expected behavior vs what's happening instead?

Is it one of these?
1. In the lobby, select a set other than Ikoria. The dropdown immediately switches back to Ikoria rather than updating to the new set.
2. In the lobby select a set other than Ikoria. The dropdown shows the newly-selected set, but when you click "Create Room" the list of sets shows Ikoria instead of the selected set.
3. In the lobby select a set other than Ikoria. The set isn't "remembered" on subsequent visits to the site.

Or some combination of the 3?

Just want to be sure I understand what I'm looking for.

**Comment by brantlc** [comment] 2020-05-16 23:19
It's 1. and 3.

**Comment by keeler** [comment] 2020-05-17 00:21
Thanks for the clarification. PR with the fix: https://github.com/dr4fters/dr4ft/pull/1039.

**Comment by tooomm** [comment] 2020-05-17 14:55
@keeler We are getting there! :)

The initial issue reported here is fixed, but I'm sorry to let you know that now there is another one now. :)
![booster selection](https://user-images.githubusercontent.com/9874850/82149012-12e79e00-9856-11ea-91d2-1cd301f70090.png)

It only happens when you visit the page for the first time. Once you change the number of packs the drop down menus appear in correct quantity, but with the first set in the list preselected, not our default.

<br>

BTW: You got autoclosing almost working :P https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Closed** 2020-05-19 15:59 UTC
Labels: bug
