### ISSUE TITLE
Bug: Issues with Custom Sets

### ISSUE THREAD

**Issue by PietroAronica** [dr4fters/dr4ft#1640] opened 2022-08-15 16:10 UTC
**Webpage**: https://dr4ft.info/

I have been trying to use a custom made cube, and while it mostly works there are a few issues I can't solve.

## Detailed Description

1. If there is a lot of text on the card, the image has a little scroll bar on the right side but it does not appear to be interactive. The rest of the card cannot be scrolled down to and read.
2. If there is already a custom card by that name, it sometimes defaults to that one. How do I ensure that it uses the XML I provide to pull my custom set rather than others?
3. How can I add images to custom cards? I have seen some custom cards have their own custom images. Can I point to an url on Imgur? Or Google Drive?
4. Some card names seem to be problematic, but I am unsure why. It seems to be names with apostrophes but rarely. There was a card named Crusher's Fists that was not accepted, but changing the name in the XML seems to solve the issue. Not a big deal and happens relatively rarely but I'd like to know why so I can avoid it.

## Further Information

[MRD_not_working.txt](https://github.com/dr4fters/dr4ft/files/9338369/MRD_not_working.txt)
[MRD_working.txt](https://github.com/dr4fters/dr4ft/files/9338375/MRD_working.txt)
These are two XML files (renamed to .txt so I could upload) that are, as far as I can tell, identical save for the name of one card. Crusher's Fists seems to not work while Fists of the Crushers does.
![Scroll](https://user-images.githubusercontent.com/22812656/184672089-42d8d57b-de2b-4dd4-9a6f-e04002d539f1.png)
This is an image of a card with text that goes beyond the box. Although there is a scroll bar, it cannot be interacted with. Also, this is an example of a card where it defaults to an existing custom card where I would like to use mine.
[CHK_itc.txt](https://github.com/dr4fters/dr4ft/files/9338411/CHK_itc.txt)
This is an xml file (again in .txt form) with a card with the same name. Although I upload it, it uses the one it already has.

**Comment by tooomm** [comment] 2022-08-22 14:36
>1. If there is a lot of text on the card, the image has a little scroll bar on the right side but it does not appear to be interactive. The rest of the card cannot be scrolled down to and read.
![Scroll](https://user-images.githubusercontent.com/22812656/184672089-42d8d57b-de2b-4dd4-9a6f-e04002d539f1.png)
This is an image of a card with text that goes beyond the box. Although there is a scroll bar, it cannot be interacted with.

I reported this before, the problem is also present for some Magic cards with more text.
Maybe @mixmix can have a look? ;)

>2. If there is already a custom card by that name, it sometimes defaults to that one. How do I ensure that it uses the XML I provide to pull my custom set rather than others?

You can try to add spaces to the end of the card name to make it differ from the already known card.

>3. How can I add images to custom cards? I have seen some custom cards have their own custom images. Can I point to an url on Imgur? Or Google Drive?

Yes, you can add your own images. dr4ft uses the database format from Cockatrice, look [there](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#custom-cards-for-old-v3-format) to learn more. The newer v4 format is also supported in case you use that already.

**Comment by PietroAronica** [comment] 2022-08-22 15:20
Thank you for your response.
1.
Thanks for looking into this.
2.
I have found an alternative workaround. Adding my custom set code after the card name in parentheses pulls the correct card.
3.
Thanks, I have gotten it to work. One more thing, do you know if transform cards can also be done this way? In regular dr4ft, transform cards show the front and it flips to the back when you hover over them. How do I replicate this beahviour with custom cards?

**Comment by tooomm** [comment] 2022-08-22 17:13
>One more thing, do you know if transform cards can also be done this way? In regular dr4ft, transform cards show the front and it flips to the back when you hover over them. How do I replicate this beahviour with custom cards?

Yes, the current database format supports that. See the above link to the Cockatrice wiki and check the v4 format.

**Comment by PietroAronica** [comment] 2022-08-24 14:07
> The current database format should support that. See the above link to the Cockatrice wiki and check the v4 format and the information about transform cards.
I have tried to do it but it fails, with same error as [this](https://github.com/dr4fters/dr4ft/issues/1614).

**Comment by tooomm** [comment] 2022-08-30 13:08
Sorry, it looks like there is a problem with exactly that not working as it should.

I suggest you comment and follow the already open bug report #1614 you linked for updates!

I'm closing this issue as all questions are answered. Feel free to reopen if that's not the case.

**Closed** 2022-08-30 13:08 UTC
Labels: bug
