### ISSUE TITLE
Bug: Unable to import from CubeCobra

### ISSUE THREAD

**Issue by JMASmith2484** [dr4fters/dr4ft#1723] opened 2023-08-08 17:15 UTC
Chrome

**Webpage**: 

## Detailed Description

Trying to import a CubeCobra ID keeps resulting in an error message

## Further Information

![Screenshot 2023-08-08 at 10 14 30 AM](https://github.com/dr4fters/dr4ft/assets/141763348/bca894c6-76a9-4230-84bd-c516ca45c18d)

**Comment by mildmongrel** [comment] 2023-09-06 01:50
Looks like a duplicate of https://github.com/dr4fters/dr4ft/issues/1709.   I addressed it with https://github.com/dr4fters/dr4ft/pull/1710 which was merged but it hasn't made its way out to dr4ft.info yet.

**Comment by ZeldaZach** [comment] 2023-09-06 04:36
I've updated the site

**Closed by ZeldaZach** 2023-09-06 04:36 UTC
Labels: bug
