### ISSUE TITLE
Clean install issue

### ISSUE THREAD

**Issue by trsbox** [dr4fters/dr4ft#67] opened 2017-11-10 20:19 UTC
Hello, I am getting this:

 sudo make run
npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/arxanas/utils.git /root/.npm/_cacache/tmp/git-clone-47a3b3c7
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-47a3b3c7': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-10T20_18_40_708Z-debug.log
Makefile:14: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by HerveH44** [comment] 2017-11-10 20:25
Hi,

What operating system do you run ? Windows/Linux/OSX ? It seems that it can't create a directory.

I don't know the solution though... @dev-id what do you think?

**Comment by trsbox** [comment] 2017-11-11 19:35
Debian.  running as sudo

**Comment by HerveH44** [comment] 2017-11-12 10:03
Ok, and if you try without sudo ? 

PS: can you close the issue is everything is fine :) ?

Thank you

**Closed** 2018-01-24 18:56 UTC
