### ISSUE TITLE
Commander Legends Double Pick

### ISSUE THREAD

**Issue by RalphNader2020** [dr4fters/dr4ft#1295] opened 2020-11-13 13:03 UTC
Hi there!

I'm looking to draft commander legends with friends on Cockatrice. From what I've read/seen, draft is usually completed by picking two cards from the pack at once. Is this a possible/not too much hassle implementation that could be done?

Thanks for considering!
Ralph

**Comment by tooomm** [comment] 2020-11-13 13:31
Duplicate of https://github.com/dr4fters/dr4ft/issues/1169, please follow there for updates!

**Closed by tooomm** 2020-11-13 13:31 UTC

**Comment by akariwhim** [comment] 2022-08-04 20:39
Still does not implement the double masters paradigm
