### ISSUE TITLE
Bug: Draftlog button missing. 

### ISSUE THREAD

**Issue by frankbrownvet** [dr4fters/dr4ft#1456] opened 2021-02-13 20:46 UTC
**Webpage**: www.dr4ft.info

Did an 8 player draft. Draft log button area was missing for me, but seemed to be present for other players of the draft. 

## Detailed Description

Refreshing the page or resizing the page did not make the draft log buttons appear. 

## Further Information

<img width="1056" alt="Screen Shot 2021-02-13 at 3 46 48 PM" src="https://user-images.githubusercontent.com/79024446/107861255-b03a2780-6e12-11eb-9c8c-f700518a9dae.png">

**Comment by tooomm** [comment] 2021-02-13 23:08
Thanks for reporting this issue @frankbrownvet!

Do you have the Game ID or the link of the draft by chance?
When did this draft take place?

Looks like https://github.com/dr4fters/dr4ft/issues/1445 is not alone anymore. :/

**Comment by frankbrownvet** [comment] 2021-02-13 23:10
This was the link. It was a few hours ago today, around 3pm EST
https://dr4ft.info/#g/7ac27b20-6e35-11eb-8586-67a1a18aa655

**Comment by mixmix** [comment] 2021-02-16 04:28
How annoying!
I've not been able to reproduce this in development , nor in production.

**Have tried:**
- cube draft
    - just entering a set of cards in input box
- choose 2 players, 1 pack, 5 cards per pack
- browsers
  - firefox
  - chromium (linux)

**Comment by tooomm** [comment] 2021-02-16 08:48
>This was the link. It was a few hours ago today, around 3pm EST
https://www.dr4ft.info/#g/7ac27b20-6e35-11eb-8586-67a1a18aa655

@ZeldaZach can you check the logs there?

**Comment by tooomm** [comment] 2022-03-07 17:25
Closing this as duplicate of #1445

**Closed by tooomm** 2022-03-07 17:25 UTC
Labels: bug
