### ISSUE TITLE
Bug: image quality hard to change

### ISSUE THREAD

**Issue by mixmix** [dr4fters/dr4ft#1490] opened 2021-03-13 03:51 UTC
Changing the image quality (on mobile, and probably desktop) doesn't work.

Eg start on low quality, turn it up to high, nothing happens. Change the sort mode and you immediately see it adjust to correct level.

Changing to text only mode works, but doesn't help image quality change

**Comment by tooomm** [comment] 2021-03-14 16:16
I can confirm. This is a recent regression. It used to update and refresh the images immediately after the quality setting got changed.

It can still be seen on the [dr4ft beta deployment](https://beta-dr4ft.herokuapp.com) which runs a build from 2021-03-01 due to the recent Heroku issues.

**Comment by tooomm** [comment] 2022-02-26 18:26
Fixed in #1585

**Closed by tooomm** 2022-02-26 18:26 UTC
Labels: bug, medium priority
