### ISSUE TITLE
Bug: draft disappears while drafting

### ISSUE THREAD

**Issue by Hyphen-ated** [dr4fters/dr4ft#1032] opened 2020-05-15 05:36 UTC
Today I was drafting with seven other people and no bots. We were using a cube list I supplied. Partway through the draft, sometime around 6:45 PDT,  the site seemed to become unresponsive, not showing new packs when it should be, so we all refreshed, as we often have to do while using the site -- usually it becomes responsive again. This time our draft disappeared, giving us all the error message "No game found with id 030ee490-964c-11ea-a392-99c8e72d674f". 

(the id was either that one or it was 38617cf0-964e-11ea-bf1e-8de64706c4b4. One of these is the draft we successfully completed afterwards and I'm not 100% sure which is which)

This happened to me once before, about a week or two ago.

**Comment by tooomm** [comment] 2020-05-15 05:54
How long was the draft running when this happened?

**Comment by Hyphen-ated** [comment] 2020-05-15 07:14
10 minutes or less

**Comment by HerveH44** [comment] 2020-05-15 07:14
Hi @Hyphen-ated what website were you using to play - dr4ft.info or beta-dr4ft.herokuapp? It seems that you were playing when the website rebooted. It may happen from time to time as we do not have any update schedule yet (but who knows for the future @ZeldaZach ?).

**Comment by Hyphen-ated** [comment] 2020-05-15 07:16
We were using dr4ft.info

**Comment by HerveH44** [comment] 2020-05-15 13:43
@ZeldaZach could you tell us what the log says? I would guess that you updated the website but it could be something else.

**Comment by rnoennig** [comment] 2020-05-15 15:54
Same happened to me twice in a row now. Nothing is shown in the javascript console. Both players are in "Waiting for the next pack..." state.
Was a "Type: Decadent Draft; Info: 36x M20" game. Game id 4d145a30-96c3-11ea-a445-457e78a678d9

**Comment by HerveH44** [comment] 2020-05-18 15:25
Hi @rnoennig and @Hyphen-ated have you been experiencing this weird behavior again since the last 3 days?

We have been updating the server since then and we may have solved this issue.

**Comment by Hyphen-ated** [comment] 2020-05-29 02:02
@HerveH44 Yes, it happened again about one minute ago. The game id was 47265340-a149-11ea-948a-0d78b30da32a

**Comment by Hyphen-ated** [comment] 2020-11-20 02:54
It happened again just now. The id was 698de9b0-2ad9-11eb-b2c4-71aa278cc214

**Comment by Hyphen-ated** [comment] 2020-12-18 02:44
It happened again just now. The id was 0b5edfa0-40d9-11eb-807d-4b571ac2e143

**Comment by ZeldaZach** [comment] 2020-12-30 17:35
We've been trying to narrow this issue down, but can't always reproduce/get it to alert us. The logs don't show any kind of crash, which is making this very difficult to diagnose.

**Comment by Hyphen-ated** [comment] 2021-01-08 02:34
It just happened again but during the pre-game lobby this time. The id was a2e1ac50-5159-11eb-846c-532aa70c921e

**Comment by HerveH44** [comment] 2021-01-19 20:51
@Hyphen-ated what do you mean by the pre-game lobby ?

**Comment by Hyphen-ated** [comment] 2021-01-19 21:16
Just that the "start game" button had not yet been clicked.

**Comment by HerveH44** [comment] 2021-01-29 19:43
Closing this issue as it doesn't provide any way we can duplicate it.

**Closed by HerveH44** 2021-01-29 19:43 UTC
Labels: bug, medium priority

**Comment by Hyphen-ated** [comment] 2021-01-29 20:20
What a slap in the face. What do you expect me to be able to provide for a defect of this kind?
